Bug Fix: When polling pod.status.start_time.
EMBL-EBI-TSI/tesk-core pull request #35
Opened 2020-11-12 09:54 UTC by cibinsb

Initially I assumed that `pod.status.start_time` value will be present when polling the status of the pod. However, there were cases when its value will be `None` (to reproduce the error, delete the storage class in k8). To prevent this bug, additional check was neccesary. Now condition is added and the generic error message will be logged.

2020-11-12 17:09 UTC, aniewielska commented
Right. But this fix is not just a fix, but it changes previous logic. The test even still says in one of the tests:
 """
        Checking if the job status is 'running' when the pod failed to start with a reason other than ImagePullBackOff.
"""
and then, you removed the condition on imagePullBackOff and changed the test result to Error.

If we need a timeout on other reasons than specified, it should rather be a separate value. It makes sense to fail fast on imagePullError (likely it will be an error in the request), but not so fast on waiting in a queue for resources.

2020-11-12 17:13 UTC, aniewielska requested changes
As in a comment in the PR (please, do not change the logic).

2020-11-17 09:35 UTC, cibinsb commented
Reverted to the previous logic, please reiew.

2020-11-18 14:53 UTC, aniewielska requested changes
Looks as if it worked. Can I ask you to squash commits, as we have effectively 6 commits now changing one line of code?

2020-11-30 18:20 UTC, aniewielska approved these changes
LGTM. I will merge it after #37, as the error comes handy in testing #37.

2020-11-30 22:04 UTC, merged